spring:
  main:
    web-application-type: none
  application:
    name: stock-batch
  profiles:
    active: local
  config:
    import:
      - optional:file:../../env.properties
      - jpa.yml
      - logging.yml
  batch:
    job:
      enabled: false
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: never

ls-investment:
  app-key: ${LS_APP_KEY:1111}
  secret-key: ${LS_SECRET_KEY:1111}
  auth-token: ${LS_AUTH_TOKEN:1111}

management:
  health:
    defaults:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: local, test
  batch:
    jdbc:
      initialize-schema: always

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false