-- stock-realtime 이 직접 읽고 쓰는 테이블만 정의한다.
-- 소유자는 stock-batch 이며, 여기 정의는 테스트용 복제본이다.

create table if not exists stock (
    id           bigint generated by default as identity primary key,
    code         varchar(255),
    name         varchar(255),
    stock_regime varchar(32),
    stock_trend  varchar(32),
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    deleted_at   timestamp(6) with time zone
);

create table if not exists stock_base_line (
    id                 bigint generated by default as identity primary key,
    price              bigint,
    strength           numeric(38, 2),
    accumulated_volume bigint,
    touch_count        bigint,
    type               varchar(32),
    stock_base_id      bigint,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    deleted_at         timestamp(6) with time zone
);

create table if not exists stock_base (
    id                           bigint generated by default as identity primary key,
    is_vcp                       boolean,
    started_at                   date,
    stage_level                  bigint not null,
    stock_base_kind              varchar(32),
    stock_id                     bigint,
    highest_resistance_line_id   bigint,
    lowest_support_line_id       bigint,
    strongest_resistance_line_id bigint,
    strongest_support_line_id    bigint,
    created_at                   timestamp(6) with time zone not null,
    updated_at                   timestamp(6) with time zone not null,
    deleted_at                   timestamp(6) with time zone
);

create table if not exists stock_anchor_point (
    id            bigint generated by default as identity primary key,
    price         bigint,
    volume        bigint not null,
    trade_date    date,
    type          varchar(32),
    stock_id      bigint not null,
    stock_base_id bigint,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    deleted_at    timestamp(6) with time zone
);

create table if not exists stock_rank_score (
    id         bigint generated by default as identity primary key,
    base_date  date,
    momentum   numeric(38, 6),
    fip        numeric(38, 6),
    up_days    integer,
    down_days  integer,
    stock_id   bigint,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone
);

create table if not exists stock_tick (
    id         bigint generated by default as identity primary key,
    stock_code varchar(255),
    trade_time timestamp(6),
    price      bigint,
    volume     bigint,
    acc_volume bigint,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone
);
