-- stock-api 가 조회하는 분석 도메인 테이블. 소유자는 stock-batch 이며 여기 정의는 테스트용 복제본이다.
-- stock-api 자신의 테이블(stock_snap_shot, stock_like, member, refresh_token)은 엔티티가 만든다.

create table if not exists stock (
    id           bigint generated by default as identity primary key,
    code         varchar(255),
    name         varchar(255),
    stock_regime varchar(32),
    stock_trend  varchar(32),
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    deleted_at   timestamp(6) with time zone
);

create table if not exists stock_daily_candle (
    id          bigint generated by default as identity primary key,
    trade_date  date,
    open_price  bigint not null,
    high_price  bigint not null,
    low_price   bigint not null,
    close_price bigint not null,
    volume      bigint not null,
    stock_id    bigint,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    deleted_at  timestamp(6) with time zone
);

create table if not exists stock_moving_average (
    id                          bigint generated by default as identity primary key,
    ma                          bigint not null,
    base_date                   date,
    stock_moving_average_period varchar(32),
    stock_id                    bigint,
    created_at                  timestamp(6) with time zone not null,
    updated_at                  timestamp(6) with time zone not null,
    deleted_at                  timestamp(6) with time zone
);

create table if not exists stock_base_line (
    id                 bigint generated by default as identity primary key,
    price              bigint,
    strength           numeric(38, 2),
    accumulated_volume bigint,
    touch_count        bigint,
    type               varchar(32),
    stock_base_id      bigint,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    deleted_at         timestamp(6) with time zone
);

create table if not exists stock_base (
    id                           bigint generated by default as identity primary key,
    is_vcp                       boolean,
    started_at                   date,
    stage_level                  bigint not null,
    stock_base_kind              varchar(32),
    stock_id                     bigint,
    highest_resistance_line_id   bigint,
    lowest_support_line_id       bigint,
    strongest_resistance_line_id bigint,
    strongest_support_line_id    bigint,
    created_at                   timestamp(6) with time zone not null,
    updated_at                   timestamp(6) with time zone not null,
    deleted_at                   timestamp(6) with time zone
);

create table if not exists stock_rank_score (
    id         bigint generated by default as identity primary key,
    base_date  date,
    momentum   numeric(38, 6),
    fip        numeric(38, 6),
    up_days    integer,
    down_days  integer,
    stock_id   bigint,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone
);

create table if not exists stock_eps (
    id                         bigint generated by default as identity primary key,
    eps                        double not null,
    quarter                    date,
    year_over_year_change_rate double,
    stock_id                   bigint,
    created_at                 timestamp(6) with time zone not null,
    updated_at                 timestamp(6) with time zone not null,
    deleted_at                 timestamp(6) with time zone
);

create table if not exists kospi_relative_strength (
    id         bigint generated by default as identity primary key,
    rs_score   integer not null,
    kospi_id   bigint,
    stock_id   bigint,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone
);

create table if not exists stock_tick (
    id         bigint generated by default as identity primary key,
    stock_code varchar(255),
    trade_time timestamp(6),
    price      bigint,
    volume     bigint,
    acc_volume bigint,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone
);
